{
 "title": "Measurements by Source and Destination",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "Source",
    "query": "{\"find\":\"terms\", \"field\":\"meta.source.hostname.keyword\", \"size\": 100000} "
   },
   {
    "name": "dest",
    "label": "Destination",
    "query": "{\"find\":\"terms\", \"field\":\"meta.destination.hostname.keyword\", \"size\": 100000} "
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "{{term pscheduler.tool.keyword}} (TCP)",
     "bucketAggs": [
      {
       "$$hashKey": "object:149",
       "fake": true,
       "field": "pscheduler.tool.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:39",
       "field": "pscheduler.start_time",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:37",
       "field": "result.throughput",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "(meta.source.hostname.keyword:$source) AND (meta.destination.hostname.keyword:$dest) AND (!test.spec.udp:true)",
     "timeField": "pscheduler.start_time"
    },
    {
     "alias": "{{term pscheduler.tool.keyword}} (UDP)",
     "bucketAggs": [
      {
       "$$hashKey": "object:1214",
       "fake": true,
       "field": "pscheduler.tool.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1198",
       "field": "pscheduler.start_time",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1196",
       "field": "result.throughput",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "(meta.source.hostname.keyword:$source) AND (meta.destination.hostname.keyword:$dest) AND (test.spec.udp:true)",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:149",
       "fake": true,
       "field": "pscheduler.tool.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:39",
       "field": "pscheduler.start_time",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:37",
       "field": "result.packets.loss",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "(meta.source.hostname.keyword:$source) AND (meta.destination.hostname.keyword:$dest) AND (test.type:rtt OR latencybg OR latency)",
     "timeField": "pscheduler.start_time"
    },
    {
     "alias": "{{term pscheduler.tool.keyword}} (UDP)",
     "bucketAggs": [
      {
       "$$hashKey": "object:848",
       "fake": true,
       "field": "pscheduler.tool.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:795",
       "field": "pscheduler.start_time",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:793",
       "field": "result.packets_sent",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": { "missing": 1 },
       "type": "sum"
      },
      {
       "$$hashKey": "object:811",
       "field": "result.packets_lost",
       "hide": true,
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "$$hashKey": "object:823",
       "field": "select field",
       "id": "4",
       "meta": {},
       "pipelineVariables": [
        { "$$hashKey": "object:834", "name": "lost", "pipelineAgg": "3" },
        { "$$hashKey": "object:839", "name": "sent", "pipelineAgg": "1" }
       ],
       "settings": { "script": "params.lost / params.sent" },
       "type": "bucket_script"
      }
     ],
     "query": "(meta.source.hostname.keyword:$source) AND (meta.destination.hostname.keyword:$dest) AND (test.type:throughput) AND (test.spec.udp:true)",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Latency (One-way)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:149",
       "fake": true,
       "field": "pscheduler.tool.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:39",
       "field": "pscheduler.start_time",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:37",
       "field": "result.latency.min",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "(meta.source.hostname.keyword:$source) AND (meta.destination.hostname.keyword:$dest) AND (test.type:latencybg OR latency)",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Round Trip Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:149",
       "fake": true,
       "field": "pscheduler.tool.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:39",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:37",
       "field": "result.rtt.min",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "(meta.source.hostname.keyword:$source) AND (meta.destination.hostname.keyword:$dest) AND (test.type:rtt)",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}