version: '3.7'
services:
    centos7:
        build:
            context: .
            dockerfile: Dockerfile-build
        tmpfs:
          - /run
          - /tmp:exec
        volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup:ro
        ports:
          - "5000:5000"
